### ISSUE TITLE
Critical Bug when looking at bundel for the first time

### ISSUE THREAD

**Issue by jolesh** [janfokke/StardewValleyDutch#8]
### Mods

- SMAPI
- Content Patcher
- StardewValleyDutch

Started a new game with the mods already installed

### How to reproduce
Go into the community center again after visiting it with Lewis and look at the bundle.

### Expected behavior

Show the unintelligible text from the bundle

### Actual behavior

- Viewed area stays at the same location (doesn't follow the player anymore)
- No walking animation anymore, player slides/flows around
- Can't leave the community center anymore (need to restart the day)

### Interesting to note

- it doesn't happen with bundles from save games, so maybe it is sth speacial because it is the first time one looks at a bundle.
- Also happens when the language is turned to English, so maybe not a problem in the translation file but somewhere else

### Error Message
Here the error message which is repeated in the console all the time:

```
[game] An error occurred in the base update loop: FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at StardewValley.Menus.Bundle..ctor(Int32 bundleIndex, String rawBundleInfo, Boolean[] completedIngredientsList, Point position, String textureName, JunimoNoteMenu menu)
   at StardewValley.Menus.JunimoNoteMenu.setUpMenu(Int32 whichArea, Dictionary`2 bundlesComplete)
   at StardewValley.Menus.JunimoNoteMenu..ctor(Int32 whichArea, Dictionary`2 bundlesComplete)
   at StardewValley.Locations.CommunityCenter.<>c__DisplayClass47_0.<checkBundle>b__0()
   at StardewValley.Network.NetMutex.Update(FarmerCollection farmers)
   at StardewValley.Locations.CommunityCenter.updateEvenIfFarmerIsntHere(GameTime time, Boolean ignoreWasUpdatedFlush)
   at StardewValley.Game1.UpdateLocations(GameTime time)
   at StardewValley.Game1._update(GameTime gameTime)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SCore.OnPlayerInstanceUpdating(SGame instance, GameTime gameTime, Action runUpdate) in SMAPI\Framework\SCore.cs:line 1117
```

**Comment by jolesh** [comment]
Except for this bug everything is working perfectly fine and it's a lot of fun. :)
The sadder it is that I can't use the community center.

**Comment by jolesh** [comment]
I guess it is the issue described [here](https://steamcommunity.com/app/413150/discussions/0/4048138220347819263/), so will try reinstalling the game...
